### PR TITLE
Include FaultCode in exception, retry if issue is with session

### PR DESCRIPTION
**Pull request by eileenmcnaughton**

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Just noting tests are now passing in travis
https://travis-ci.org/github/eileenmcnaughton/silverpop-php-connector/builds/748253712

**Comment by eileenmcnaughton** [comment]
Yay - I was just trying to figure out how to include from my repo but you have saved me that. If you can tag a release would be even better :-)

**Comment by mrmarkfrench** [comment]
Just a thought for this type of use case in the future: I might have preferred to handle the retry differently. They way you've set it up works as intended (and as you'll note, I've already merged your PR), but I might have looked to implement by providing a retry count as an optional param, and a list of codes to retry on. If the code matches, and the retry count is greater than zero, recurse, subtracting one from the retry count. This would provide a more flexible solution to other use cases, and with default values you could still have it handle things just as it does in your solution without any change to code calling this method.

Anyway, thanks for your continued contributions!

**Comment by mrmarkfrench** [comment]
I'll have a tagged release out for you shortly here.

**Comment by eileenmcnaughton** [comment]
@mrmarkfrench yeah - it seems to be the same error between session time out & invalid - so I figured that if it were the former one retry would be enough to recover - but you are right it could definitely be extended as you say

**Comment by mrmarkfrench** [comment]
Version 1.4.0 is live. Happy coding!

**Pull request merged**
