### PR TITLE
add: specify date format for list export

### PR DESCRIPTION
**Pull request by ilanco**
Hi Mark,

Added option to change date format when exporting a list.

### CODE REVIEW

**Comment by mrmarkfrench** [comment]
While I understand the desire to be able to specify a date format (and the Silverpop API certainly seems to accept a parameter to do so), this would be a breaking change, as it will alter the parameter order on a public function. Might I suggest a method to set the date format, and then using whatever date format is set on the connector when making the call from within the exportList() method?

It seems unlikely that most users would need to specify different date formats from one list export to another, so a single setting meets most use cases, and it means that anybody who pulls down an updated version of this code will not need to change their implementation to have it continue working.

Also, is the default date format you specified the default that Silverpop returns if you don't ask them for a different one? If so, great. If not, let's change the default to match the default in Silverpop so that anybody who pulls down updated code post-merge doesn't suddenly get their dates returned to them in a new and unexpected format.

**Comment by ilanco** [comment]
Hi Mark,

I agree and update the code accordingly. The default date for Silverpop is indeed MM/dd/yyyy and as far as i could tell, not dependent on the user setting.

**Comment by mrmarkfrench** [comment]
Great. I'll look forward to seeing an update, then.

**Comment by ilanco** [comment]
Already updated

**Pull request merged**
